FROM python:3.10

WORKDIR /app

COPY requirements.txt .

RUN python -m venv /opt/venv && /opt/venv/bin/pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PATH="/opt/venv/bin:$PATH"

CMD ["python", "index.py"]
